# Generated by Django 5.2.15 on 2026-06-15 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('set_number', models.PositiveIntegerField()),
                ('stand_number', models.PositiveIntegerField()),
                ('profile', models.PositiveIntegerField()),
                ('initial_diameter', models.DecimalField(decimal_places=2, max_digits=8)),
                ('current_diameter', models.DecimalField(decimal_places=2, max_digits=8)),
                ('current_status', models.CharField(choices=[('CREATED', 'Добавлен'), ('REGRINDING', 'Переточка'), ('ON_BEARING', 'В подшипниках'), ('ON_PILLOW', 'В подушках'), ('ASSEMBLED', 'Собран'), ('ON_STAND', 'В клети'), ('ON_MILL', 'На стане'), ('ON_COMPLETED', 'Отработан'), ('SCRAPPED', 'Списан')], default='CREATED', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.TextField(blank=True, verbose_name='Ответственный')),
            ],
        ),
        migrations.CreateModel(
            name='RollHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('status', models.CharField(choices=[('CREATED', 'Добавлен'), ('REGRINDING', 'Переточка'), ('ON_BEARING', 'В подшипниках'), ('ON_PILLOW', 'В подушках'), ('ASSEMBLED', 'Собран'), ('ON_STAND', 'В клети'), ('ON_MILL', 'На стане'), ('ON_COMPLETED', 'Отработан'), ('SCRAPPED', 'Списан')], max_length=30, verbose_name='Статус')),
                ('old_diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Старый диаметр')),
                ('new_diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Новый диаметр')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('employee', models.TextField(blank=True, verbose_name='Ответственный')),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='rolls.roll', verbose_name='Вал')),
            ],
            options={
                'verbose_name': 'История вала',
                'verbose_name_plural': 'История валов',
                'ordering': ['-operation_date'],
            },
        ),
    ]
