# Generated by Django 5.2.15 on 2026-06-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='roll',
            name='stand_number',
            field=models.PositiveIntegerField(),
        ),
    ]
